import {Login, Register, ResetPwd} from '/components'
import {LoginValid, PwdValid, RegValid} from '/components'
import { AdminHeader, StaffHeader } from '/components/Header'
import 'components/Epic2Filter'
import './MainPage.css'